#! /bin/sh
# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗  Author: ThePiGuy
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝


pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
picom &
feh --bg-fill Documents/wallpaper.jpg &
flameshot &
pulseaudio --start 
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	2
#bspc config window_gaps		7

bspc config focused_border_color "#65b3f7"
bspc config normal_border_color "#0c576e"

bspc config presel_feedback_color "#65b3f7"

#bspc rule -a PMenu state=floating
bspc rule -a Pavucontrol state=floating
